practica12/ejemplo/ejemplo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('opiniones/', include('opiniones.urls')),
    path('admin/', admin.site.urls),
]

practica12/ejemplo/opiniones/urls.py
"""
Definición de las rutas de la app, enlazando las funciones que las manejan
"""
from django.urls import path
from opiniones import views

# Imprescindible dar un nombre para crear un namespace y poder referirse a estas rutas como
# opiniones:index, opiniones:login, etc.
app_name = "opiniones"

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.loginfunct, name='login'),
    path('logout', views.logoutfunct, name='logout'),
    path('nueva_opinion', views.nueva_opinion, name='nueva_opinion'),
]

practica12/ejemplo/opiniones/models.py
"""
Fichero con la definición de los modelos para el ORM
"""

from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError


class Opinion(models.Model):
    """Modelo para almacenar la opinion de un usuario"""
    # Identificador único autogenerado
    ident = models.BigAutoField(primary_key=True)

    # Puntuación entre 0 y 10
    puntuacion = models.SmallIntegerField(validators=[MinValueValidator(0),
                                                      MaxValueValidator(10)])

    # Texto de máximo 200 caracteres
    texto = models.CharField(max_length=200)

    # Al crear una opinion se pone la fecha actual
    fecha = models.DateTimeField(auto_now_add=True)

    # Referencia a un usuario del sistema.
    # Si se elimina el usuario, este campo se pone a NULL
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, null=True,
                              blank=True, on_delete=models.SET_NULL)

    def clean(self):
        if self.puntuacion < 5 and len(self.texto.split()) < 5:
            raise ValidationError("Puntuacion negativa poco motivada")


    def __str__(self):
        """Para mostrar detalles en la interfaz admin"""
        return f"Opinión({self.puntuacion}, {self.texto}, {self.autor})"

practica12/ejemplo/opiniones/forms.py
"""
Definición de formularios para validación
"""
from django import forms
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    """Formulario para autenticar usuarios"""
    username = forms.CharField(label='Nombre de usuario', max_length=100)
    password = forms.CharField(label='Contraseña', max_length=100, widget=forms.PasswordInput)


class OpinionForm(forms.Form):
    """Formulario para añadir opiniones"""
    puntuacion = forms.IntegerField(min_value=0, max_value=10, required=True, label="Tu puntuación")
    texto = forms.CharField(max_length=200, label='Tu comentario')

    def clean_texto(self):
        """Limpieza personalizada: texto en minúsculas"""
        return self.cleaned_data['texto'].lower()

    def clean(self):
        """ Validación de varios campos: puntuacion y texto """
        cleaned_data = super().clean()
        puntuacion_clean = cleaned_data.get("puntuacion")
        texto_clean = cleaned_data.get("texto")

        if (puntuacion_clean and texto_clean and puntuacion_clean < 5 and
                len(texto_clean.split()) < 5):
            raise ValidationError(
                "Puntuación negativa (<5) poco motivada. Es necesario incluir 5 o más palabras.")

practica12/ejemplo/opiniones/views.py
"""
Fichero con las funciones que manejan las peticiones HTTP
"""
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponseBadRequest
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET, require_http_methods
from django.core.exceptions import ValidationError

from opiniones.forms import LoginForm, OpinionForm
from opiniones.models import Opinion


@require_GET
def index(request):
    """ Página principal, muestra las opiniones ordenadas por fecha """
    opiniones = Opinion.objects.order_by('-fecha')
    return render(request, "opiniones.html", {'opiniones': opiniones})


@require_http_methods(["GET", "POST"])
def loginfunct(request):
    """ Muestra el formulario (GET) o recibe los datos y realiza la autenticacion (POST) """
    if request.method == "GET":
        form = LoginForm()
        return render(request, "login.html", {'login_form': form})

    # Carga el formulario desde los datos de la petición y lo valida
    form = LoginForm(request.POST)
    if not form.is_valid():
        return HttpResponseBadRequest(f"Error en los datos del formulario: {form.errors}")

    # Toma los datos limpios del formulario
    username = form.cleaned_data['username']
    password = form.cleaned_data['password']

    # Realiza la autenticación
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)  # Registra el usuario en la sesión
        return redirect(reverse('opiniones:index'))

    return HttpResponseBadRequest("Usuario o contraseña incorrectos")


@require_GET
def logoutfunct(request):
    """ Elimina al usuario de la sesión actual """
    logout(request)  # Elimina el usuario de la sesión
    return redirect(reverse('opiniones:index'))


@login_required(login_url='opiniones:login')
@require_http_methods(["GET", "POST"])
def nueva_opinion(request):
    """ Muestra el formulario de nueva opinión (GET) o
        recibe el formulario y añade la opinión (POST)
    """
    if request.method == "GET":
        form = OpinionForm()
        return render(request, "nueva_opinion.html", {'opinion_form': form})

    form = OpinionForm(request.POST)
    if not form.is_valid():
        return HttpResponseBadRequest(f"Error en los datos del formulario: {form.errors}")
    punt_f = form.cleaned_data['puntuacion']
    texto_f = form.cleaned_data['texto']

    # Crea un objeto ORM a partir de los datos limpios del formulario y lo salva en la BD
    opinion = Opinion(puntuacion=punt_f, texto=texto_f, autor=request.user)
    try:
        opinion.full_clean()
        opinion.save()
    except ValidationError:
        return HttpResponseBadRequest("Opinión mal formada")

    return redirect(reverse('opiniones:index'))

practica12/ejemplo/opiniones/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}TITULO{% endblock %}
    </title>
</head>
<body>
<h1>Opiniones de la exposición</h1>
<p>
{% if request.user.username %}
<a href="{% url 'opiniones:nueva_opinion' %}"><button type="button">Añadir opinión</button></a>
<a href="{% url 'opiniones:logout' %}"><button type="button">Salir</button></a>
{% else %}
<a href="{% url 'opiniones:login' %}"><button type="button">Acceder</button></a>
{% endif %}
</p>
{% if request.user.username %}
<p>Bienvenido {{request.user.username}}</p>
{% endif %}
{% block content %}
CONTENIDO
{% endblock %}
</body>
</html>

practica12/ejemplo/opiniones/templates/login.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<form action="{% url 'opiniones:login' %}" method="post">
<table>
{{ login_form }}
</table>
{% csrf_token %}
<button type="submit">Entrar</button>
</form>
</body>
</html>

practica12/ejemplo/opiniones/templates/nueva_opinion.html
{% extends "base.html" %}

{% block title %}
Añadir nueva opinión
{% endblock %}
{% block content %}
<h2>Añadir nueva opinión</h2>
<form action="{% url 'opiniones:nueva_opinion' %}" method="post">
<table>
{{ opinion_form }}
</table>
{% csrf_token %}
<button type="submit">Añadir opinión</button>
</form>
{% endblock %}

practica12/ejemplo/opiniones/templates/opiniones.html
{% extends "base.html" %}

{% block title %}
Opiniones
{% endblock %}
{% block content %}
<ul>
{% for opinion in opiniones %}
    <li>{{opinion.texto}} -- {{opinion.autor.first_name}} ({{opinion.autor.username}})<br/>
        {{opinion.fecha}}
    </li>
{% endfor %}
</ul>
{% endblock %}