practica12/giw/giw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/preguntas/')),  # Redirige la raíz a /preguntas/
    path('preguntas/', include('preguntas.urls')),
    path('admin/', admin.site.urls),
]

practica12/giw/preguntas/urls.py
"""
Definición de las rutas de la app, enlazando las funciones que las manejan
"""
from django.urls import path
from preguntas import views

app_name = "preguntas"

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.loginfunction, name='login'),
    path('logout', views.logoutfunction, name='logout'),
    path('', views.index, name='ver_preguntas'),
    path('<int:id>', views.nueva_respuesta, name='detalle_pregunta'),
    path('nueva_pregunta', views.nueva_pregunta, name='nueva_pregunta'),
]

practica12/giw/preguntas/models.py
"""
Fichero con la definición de los modelos para el ORM
"""
from django.db import models
from django.conf import settings
from django.utils.html import escape

# Create your models here.
class Pregunta(models.Model):
    """Modelo para almacenar las preguntas de los usuarios"""
    id = models.BigAutoField(primary_key=True, null=False)
    titulo = models.CharField(max_length=250, null=False)
    texto = models.TextField(max_length=5000, null=False)
    fecha = models.DateTimeField(auto_now_add=True, null=False)
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def num_respuestas(self):
        """Devuelve el número de respuestas de la pregunta"""
        return self.respuesta_set.count()

    def clean(self):
        self.titulo = escape(self.titulo)
        self.texto = escape(self.texto)

class Respuesta(models.Model):
    """Modelo para almacenar las respuestas de los usuarios"""
    id = models.BigAutoField(primary_key=True, null=False)
    texto = models.TextField(max_length=5000, null=False)
    fecha = models.DateTimeField(auto_now_add=True, null=False)
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)

    def clean(self):
        self.texto = escape(self.texto)

practica12/giw/preguntas/forms.py
"""
Definición de formularios para validación
"""
from django import forms
# from django.core.exceptions import ValidationError

class LoginForm(forms.Form):
    """Formulario para autenticar usuarios"""
    username = forms.CharField(label='Nombre de usuario', max_length=100)
    password = forms.CharField(label='Contraseña', max_length=100, widget=forms.PasswordInput)

class PreguntaForm(forms.Form):
    """Formulario para crear una nueva pregunta"""
    titulo = forms.CharField(label='Titulo')
    text = forms.CharField(label='Pregunta')

class RespuestaForm(forms.Form):
    """Formulario para crear una nueva respuesta a una pregunta"""
    texto = forms.CharField(label='Respuesta', max_length=5000, widget=forms.Textarea)

practica12/giw/preguntas/views.py
"""
Fichero con las funciones que manejan las peticiones HTTP
"""
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.http import HttpResponseBadRequest
from django.core.exceptions import ValidationError
from .models import Pregunta, Respuesta
from .forms import LoginForm, PreguntaForm, RespuestaForm

# Create your views here.
@require_GET
def index(request):
    """ Página principal, muestra las prguntas ordenadas por fecha """
    preguntas = Pregunta.objects.order_by('-fecha')
    return render(request,
                  "listar_preguntas.html",
                  {'preguntas': preguntas, 'pregunta_form': PreguntaForm})

@require_http_methods(["GET", "POST"])
def loginfunction(request):
    """ Muestra el formulario (GET) o recibe los datos y realiza la autenticacion (POST) """
    if request.method == "GET":
        form = LoginForm()
        return render(request, "login.html", {'login_form': form})

    form = LoginForm(request.POST)
    if not form.is_valid(): #Valida el fomulario
        return HttpResponseBadRequest(f"Error en los datos del formulario: {form.errors}")

    username = form.cleaned_data['username']
    password = form.cleaned_data['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect(reverse('preguntas:index'))

    return render(request, 'login.html', {'error': 'Usuario o contraseña no válidos'})


@require_GET
def logoutfunction(request):
    """ Elimina al usuario de la sesión actual """
    logout(request)
    return redirect(reverse('preguntas:index'))

@login_required(login_url='preguntas:login')
@require_POST
def nueva_pregunta(request):
    """ 
        Añade la pregunta (POST)
    """

    form = PreguntaForm(request.POST)
    if not form.is_valid():
        return HttpResponseBadRequest(f"Error en los datos del formulario: {form.errors}")
    form_titulo = form.cleaned_data['titulo']
    form_texto = form.cleaned_data['text']

    # Crea un objeto ORM a partir de los datos limpios del formulario y lo salva en la BD
    pregunta = Pregunta(titulo=form_titulo, texto=form_texto, autor=request.user)
    try:
        pregunta.full_clean()
        pregunta.save()
    except ValidationError:
        return HttpResponseBadRequest("Pregunta mal formada")

    return redirect(reverse('preguntas:index'))

@login_required(login_url='preguntas:login')
@require_http_methods(["POST", "GET"])
def nueva_respuesta(request, id):
    """
    Permite que un usuario autenticado añada una respuesta a una pregunta existente
    NOTA: si utilizamos cualquier otro nombre para el argumento id, la aplicación falla
    """
    pregunta = get_object_or_404(Pregunta, id=id)
    if request.method == "GET":
        # Mostrar un formulario vacío si se accede por GET
        respuestas = pregunta.respuesta_set.all().order_by('-fecha')
        form = RespuestaForm()
        return render(request, 'detalle_pregunta.html', {'pregunta': pregunta,
                                                         'respuestas':respuestas, 
                                                         'respuesta_form': form})

    form = RespuestaForm(request.POST)
    if not form.is_valid():
        return HttpResponseBadRequest(f"Error en los datos del formulario: {form.errors}")

    texto = form.cleaned_data['texto']

    respuesta = Respuesta(texto=texto, autor=request.user, pregunta=pregunta)
    try:
        respuesta.full_clean()
        respuesta.save()
    except ValidationError:
        return HttpResponseBadRequest('Respuesta mal formada')

    return redirect(reverse('preguntas:detalle_pregunta', args=(id,)))

practica12/giw/preguntas/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}La web para preguntas y respuestas{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/preguntas.css' %}">
</head>
<body>
    <header>
        <h1>La web para preguntas y respuestas</h1>
        <nav>
            {% if request.user.username %}
                <p>Bienvenido {{request.user.username}}</p>
                <a class="btn-nav-session" href="{% url 'preguntas:logout' %}">Cerrar sesión</a>
                <a class="btn-nav-session" href="{% url 'preguntas:ver_preguntas' %}">Ver preguntas</a>
            {% else %}
                <p>No autenticado</p>
                <a class="btn-nav-session" href="{% url 'preguntas:login' %}">Iniciar sesión</a>
            {% endif %}
        </nav>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>
</body>
</html>

practica12/giw/preguntas/templates/detalle_pregunta.html
{% extends "base.html" %}
{% load date_filters %}
{% block title %} Añadir nueva respuesta {% endblock %}
{% block content %}
    <h2>{{ pregunta.titulo }} -- {{ pregunta.autor }}  ({{ pregunta.fecha|formato_fecha}})</h2>
    <p> {{ pregunta.texto }} </p>
    {% if respuestas %}
    <h2>Respuestas</h2>
    <ol>
        {% for respuesta in respuestas %}
            <li>
                {{ respuesta.texto }} <br>
                {{ respuesta.autor }} ({{ respuesta.fecha }}) 
            </li>
        {% endfor %}
    </ol>
    {% endif %}
    <h2>Añadir nueva respuesta</h2>
    <form action="{% url 'preguntas:detalle_pregunta' pregunta.id %}" method="post">
        <table>
            {{ respuesta_form }}
        </table>
        {% csrf_token %}
        <button type="submit">Añadir respuesta</button>
    </form>
{% endblock %}

practica12/giw/preguntas/templates/listar_preguntas.html
{% extends 'base.html' %}
{% load date_filters %}
{% block title %}Preguntas{% endblock %}
{% block content %}
<h2>Preguntas</h2>
<ul>
    {% for pregunta in preguntas %}
        <li>
            <a href="{% url 'preguntas:detalle_pregunta' pregunta.id %}">{{ pregunta.titulo }}</a> 
            -- 
            {{ pregunta.autor }} 
            ({{ pregunta.fecha|formato_fecha}})<br>
            {{ pregunta.num_respuestas }} Respuestas
        </li>
    {% endfor %}
</ul>
{% if request.user.username %}
    <h2>Añadir nueva pregunta</h2>
    <form action="{% url 'preguntas:nueva_pregunta' %}" method="post">
        {{ pregunta_form }}
        {% csrf_token %}
        <button type="submit">Añadir pregunta</button>
    </form>
{% endif %}
{% endblock %}

practica12/giw/preguntas/templates/login.html
{% extends 'base.html' %}
{% block content %}
{% if error %}
    <h1>{{ error }}</h1>
{% else %}
    <form action="{% url 'preguntas:login' %}" method="post">
        <div>
        {{ login_form }}
        </div>
        {% csrf_token %}
        <button type="submit">Iniciar sesión</button>
    </form>
{% endif %}
{% endblock %}